import {describe,it,expect} from 'vitest';
import {computeDashboardMetrics} from '@/lib/dashboardMetrics';
import {financialAnalyticsSchema,financialBounds,financialDay,periodReceiptTotals,openFinancialInstallments} from '@/lib/financialAnalytics';
import {installmentOutstanding} from '@/lib/reportMetrics';
const now=new Date('2026-08-31T22:00:00-03:00');
const contract={id:'c1',capital:1000,total_interest:200,num_installments:10,status:'active',daily_interest_percent:4,clients:{name:'Teste'}};
const installment={id:'i1',contract_id:'c1',amount:100,paid_amount:40,paid_principal:30,due_date:'2026-08-30T12:00:00-03:00',status:'overdue'};
function cash(){return financialAnalyticsSchema.parse({wallet:{as_of:now.toISOString(),financial_day:'2026-08-31',totals:{inflows:100,outflows:1000,capital:0,withdrawals:0,receipts:100,disbursements:1000,ledger_expenses:0,manual_expenses:0,principal:80,profit:20,unclassified:0,undated_amount:0,legacy_gap_amount:0,balance:-900},period:{inflows:100,outflows:1000,previous_inflows:0,previous_outflows:0,opening_balance:0,closing_balance:-900},forecast:{d7:64,d30:64,d90:64},timeline:[],timeline_count:0,warnings:{undated_amount:0,legacy_gap_amount:0,unlinked_receipts:0,cash_above_installments:0,future_amount:0,recorded_profit:0}},
 receipts:[{id:'r2',contract_id:'c1',client_id:'x',installment_id:'i1',date:'2026-09-01T01:00:00Z',day:'2026-08-31',amount:60,principal:50,interest:10,fees:0,unclassified:0,description:'Quitação',category:null},{id:'r1',contract_id:'c1',client_id:'x',installment_id:'i1',date:'2026-07-30T12:00:00-03:00',day:'2026-07-30',amount:40,principal:30,interest:10,fees:0,unclassified:0,description:'Parcial',category:null}],
 disbursements:[],expenses:[],capital:[{contract_id:'c1',disbursed:1000,returned:80,outstanding:920}],warnings:{contracts_without_disbursement:0,unlinked_principal:0}});}
describe('regressões financeiras entre telas',()=>{
 it('recebido inclui parcial e preserva histórico quando contrato termina',()=>{const report=cash();const a=computeDashboardMetrics({contracts:[contract],installments:[installment],clients:[],goals:[],cash:report},now);const b=computeDashboardMetrics({contracts:[{...contract,status:'completed'}],installments:[{...installment,status:'paid',paid_amount:100}],clients:[],goals:[],cash:report},now);expect(a.totalReceived).toBe(100);expect(b.totalReceived).toBe(100);expect(b.paidTodayAmount).toBe(60);expect(b.totalProfitAmount).toBe(20);expect(b.capitalNaRua).toBe(920);});
 it('capital usa liberação e composição comprovadas, não rateio da parcela',()=>{const report=cash();const metrics=computeDashboardMetrics({contracts:[contract],installments:[installment],clients:[],goals:[],cash:report},now);expect(metrics.capitalNaRua).toBe(920);expect(metrics.totalProfitAmount).toBe(20);});
 it('parcial com encargo gera o mesmo saldo do relatório, painel e cobrança',()=>{const rows=openFinancialInstallments([contract],[installment],now);expect(rows[0].amount).toBe(64);expect(installmentOutstanding({...installment,contracts:contract},now)).toBe(64);const metrics=computeDashboardMetrics({contracts:[contract],installments:[installment],clients:[],goals:[],cash:cash()},now);expect(metrics.pendingReceivable).toBe(64);expect(metrics.totalOverdueAmount).toBe(64);});
 it('acordo congela encargo, multa diária e teto são respeitados',()=>{const row={...installment,late_fee:7,pre_settlement_snapshot:{}};expect(openFinancialInstallments([contract],[row],now)[0].amount).toBe(67);expect(openFinancialInstallments([{...contract,daily_penalty_type:'fixed',daily_penalty_value:3}],[installment],now)[0].amount).toBe(67);expect(openFinancialInstallments([{...contract,max_interest_cap_percent:2}],[installment],now)[0].amount).toBe(62);});
 it('saldo cancelado não vira cobrança, recibo cancelado permanece caixa',()=>{expect(openFinancialInstallments([{...contract,status:'cancelled'}],[installment],now)).toEqual([]);expect(cash().capital[0].outstanding).toBe(920);});
 it('períodos separam eventos e não transferem parcial antigo para a quitação',()=>{const report=cash();expect(periodReceiptTotals(report.receipts,'2026-07-01','2026-07-31').received).toBe(40);expect(periodReceiptTotals(report.receipts,'2026-08-01','2026-08-31').received).toBe(60);});
 it('noite brasileira não vira recebido de amanhã',()=>{expect(financialDay(now)).toBe('2026-08-31');const m=computeDashboardMetrics({contracts:[contract],installments:[],clients:[],goals:[],cash:cash()},now);expect(m.paidTodayAmount).toBe(60);expect(m.weeklyActivity.at(-1)?.count).toBe(1);});
 it('virada do dia recalcula saldo e hoje sem alterar os dados',()=>{const input={contracts:[contract],installments:[installment],clients:[],goals:[],cash:cash()};expect(computeDashboardMetrics(input,new Date('2026-09-01T00:01:00-03:00')).paidTodayAmount).toBe(0);expect(computeDashboardMetrics(input,new Date('2026-09-01T00:01:00-03:00')).totalOverdueAmount).toBe(68.16);});
 it('limite exclusivo inclui último dia inteiro em São Paulo',()=>{expect(financialBounds('2026-08-01','2026-08-31')).toMatchObject({startDateTime:'2026-08-01T03:00:00.000Z',endDateTime:'2026-09-01T03:00:00.000Z'});});
});
